
openapi: "3.0.3"

info:
  version: 2.0
  title: Business Income Source Summary (MTD)
  description: |
    # Overview
    This API allows a developer to retrieve a summary of income and expenditure for a specified self-employment, or property business for a given tax year.
  
    For information on how to connect to this API [see the Income Tax MTD end-to-end service guide](https://developer.service.hmrc.gov.uk/guides/income-tax-mtd-end-to-end-service-guide/).

    # Send fraud prevention data
    HMRC monitors transactions to help protect your customers' confidential data from criminals and fraudsters. 

    <div class="govuk-warning-text warning-icon-fix">
      <span class="govuk-warning-text__icon warning-icon-ui-fix" aria-hidden="true">!</span>
      <strong class="govuk-warning-text__text">
      <span class="govuk-warning-text__assistive">Warning</span>
      You are required by law to submit header data for this API. This includes all associated APIs and endpoints.
      </strong>
    </div>
  
    [Check the data you need to send](/guides/fraud-prevention/). You can also use the [Test API](/api-documentation/docs/api/service/txm-fph-validator-api/1.0) during initial development and as part of your quality assurance checks.
  
    # Versioning
      When an API changes in a way that is backwards-incompatible, we increase the version number of the API. 
      See our [reference guide](/api-documentation/docs/reference-guide#versioning) for more on versioning.

    # Errors
    We use standard HTTP status codes to show whether an API request succeeded or not. They are usually in the range:

    - 200 to 299 if it succeeded, including code 202 if it was accepted by an API that needs to wait for further action
    - 400 to 499 if it failed because of a client error by your application
    - 500 to 599 if it failed because of an error on our server
    
    Errors specific to each API are shown in the Endpoints section, under Response. See our [reference guide](https://developer.service.hmrc.gov.uk/api-documentation/docs/reference-guide#errors) for more on errors.
    
    Single errors will be returned in the following format:<br>
    ```
    {
      "code": "FORMAT_FIELD_NAME",
      "message": "The provided FieldName is invalid"
    }
    ```
      
    Where possible, multiple errors will be returned with `INVALID_REQUEST` in the following format:<br>
    ```
    {
      "code": "INVALID_REQUEST",
      "message": "Invalid request",
      "errors": [
        {
          "code": "RULE_FIELD_NAME",
          "message": "The provided FieldName is not allowed"
        },
        {
          "code": "FORMAT_FIELD_NAME",
          "message": "The provided FieldName is invalid"
        }
      ]
    }
    ```
    
    # Changelog
    
    You can find the changelog in the [self-assessment-biss-api](https://github.com/hmrc/self-assessment-biss-api/wiki/Changelog) GitHub wiki.
    
    # Support
    
    * Raise non-technical or platform-related issues with the [Software Development Support Team (SDST)](https://developer.service.hmrc.gov.uk/developer/support).
    * Raise technical issues on the [self-assessment-biss-api](https://github.com/hmrc/self-assessment-biss-api/issues) GitHub page.
    
    # Testing
    
    You can use the sandbox environment to <a href="/api-documentation/docs/testing">test this API</a>. You can use the <a href="/api-documentation/docs/api/service/api-platform-test-user/1.0">Create Test User API</a> or it's frontend service to create test users.
  
    It may not be possible to test all scenarios in the sandbox. You can test some scenarios by passing the Gov-Test-Scenario header. Documentation for each endpoint includes a **Test data** section, which explains the scenarios that you can simulate using the Gov-Test-Scenario header.
    
    If you have a specific testing need that is not supported in the sandbox, contact <a href="/developer/support">our support team</a>.
    
    Some APIs may be marked \[test only\]. This means that they are not available for use in production and may change.

servers:
  - url: https://test-api.service.hmrc.gov.uk
    description: Sandbox
  - url: https://api.service.hmrc.gov.uk/
    description: Production

components:
  responses:

#    badOrExpiredTokenResponse:
#      description: |
#        Bad or expired token.
#        This can happen if the user or HMRC revoked or expired an access token.
#        To fix, you should re-authenticate the user.
#      content:
#        application/json:
#          example:
#    forbiddenResponse:
#      description: |
#        Bad OAuth request (wrong consumer key, bad nonce, expired
#        timestamp...). Unfortunately, re-authenticating the user won't help here.
#      content:
#        application/json:
#          example:
  parameters:


#    acceptHeader:
#      name: Accept
#      in: header
#      schema:
#        type: string
#        enum: [
#            "application/vnd.hmrc.1.0+json",
#            "application/vnd.hmrc.1.0+xml"
#        ]
#      required: true
  securitySchemes:
    user restricted:
      type: oauth2
      description: HMRC supports OAuth 2.0 for authenticating User-restricted API requests
      flows:
        authorizationCode:
          authorizationUrl: https://api.service.hmrc.gov.uk/oauth/authorize
          tokenUrl: https://api.service.hmrc.gov.uk/oauth/token
          refreshUrl: https://api.service.hmrc.gov.uk/oauth/refresh
          scopes:
            write:self-assessment: Some textual description
            read:self-assessment: Some textual description
paths:
  /hello/world:
    get:
      summary: Say hello world
      description: |
        A simple example for integrating with an unrestricted service.

        Any request to this endpoint initiates a 'Hello World' response.
      tags:
        - api-example-microservice
      parameters:
        - $ref: '#/components/parameters/acceptHeader'
      responses:
        200:
          description: "OK Response"
          content:
            application/json:
              example:
                {
                  "message" : "Hello World"
                }

  /hello/user:
    get:
      summary: Say hello user
      description: |
        A simple example for integrating with a user-restricted service, using an OAuth 2.0 `access_token`.

        Any authorised request to this endpoint initiates a 'Hello User' response.
      tags:
        - api-example-microservice
      parameters:
        - $ref: '#/components/parameters/acceptHeader'
      responses:
        200:
          description: "OK Response"
          content:
            application/json:
              example:
                {
                  "message" : "Hello User"
                }
        401:
          description: "UNAUTHORISED Response"
          content:
            application/json:
              example:
                {
                  "code": "MISSING_CREDENTIALS",
                  "message": "Authentication information is not provided"
                }
      security:
        - userScheme:
            - hello

  /hello/application:
    get:
      summary: Say hello application
      description: |
        A simple example for integrating with an application-restricted service, using an OAuth 2.0 `access_token`.

        Any authorised request to this endpoint initiates a 'Hello Application' response.

      tags:
        - api-example-microservice
      parameters:
        - $ref: '#/components/parameters/acceptHeader'
      responses:
        200:
          description: "OK Response"
          content:
            application/json:
              example:
                {
                  "message" : "Hello Application"
                }
        401:
          description: "UNAUTHORISED Response"
          content:
            application/json:
              example:
                {
                  "code": "MISSING_CREDENTIALS",
                  "message": "Authentication information is not provided"
                }
      security:
        - appScheme: []

  /individuals/self-assessment/income-summary/{nino}/{typeOfBusiness}/{taxYear}/{businessId}:
#    $ref: "./retrieveBusinessIncome.yaml"
    get:
      summary: Retrieve a Business Income Source Summary (BISS)
      description: |
        This endpoint allows a developer to retrieve a running (year-to-date) summary of the income and expenditure for a specified self-employment, or property business during a tax year. A National Insurance number, business ID, tax year and type of business are required.

        Scenario simulations using Gov-Test-Scenario headers is only available in the sandbox environment.

        | Header Value (Gov-Test-Scenario) | Scenario                                                  |
        |----------------------------------|-----------------------------------------------------------|
        | N/A - DEFAULT                    | Simulates success response with profit.                   |
        | NOT_FOUND                        | Simulates the scenario where no data is found.            |
        | LOSS                             | Simulates success response with loss.                     |
        | NO_INCOME_SUBMISSIONS_EXIST      | Simulates the scenario where no income submissions exist. |
      tags:
        - not default
      parameters:
      - $ref: './pathParameters.yaml#/components/parameters/nino'
      - $ref: './pathParameters.yaml#/components/parameters/typeOfBusiness'
      - $ref: './pathParameters.yaml#/components/parameters/taxYear'
      - $ref: './pathParameters.yaml#/components/parameters/businessId'
      - $ref: './headers.yaml#/components/parameters/acceptHeader'
      - $ref: './headers.yaml#/components/parameters/contentTypeJson'
      - $ref: './headers.yaml#/components/parameters/testScenarioHeader'
      responses:
        "200":
          description: "OK Response"
          content:
            application/json:
              example:
                {
                  "message": "Hello User"
                }
      security:
      - user restricted:
          - read:self-assessment
